#This is a YAML file (full form of "YAML" -> YAML Ain't Markup Language)
# The precedence works like ->
#command line argument(--key=value) -> application.properties -> application.yml
spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb+srv://subratasantra9638:Subrata%402003@cluster0.moq4x8t.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

  #  for the mail sender
  mail:
    host:
    port: 587
    username: example@gmail.com
    password: xxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  #-----------------------------------------------------------------
  profile:
    active: dev

#There is a thing "PROFILE" -> you can define multiple properties for different environment i.e. dev & prod
#you just have to devine which one you want to use to run the application in the application.yml file
#This can also be defined in the command line through mvn and then java jar file
#-----------------------------------------------------------------


#-----------------------------------------------------------------
#@Value Notation using . Accessing the application.yml value in the application as a variable
weather:
  api:
    key:  b19fd1808ff0152155fbf2bc991e8097



